--CURSOR HAS TWO TYPES 
--IMPLICIT
--EXPLICIT



--FETCH FIRST_NAME,LAST_NAME,EXPERIENCE OF USER DEFINED DEPARTMENT
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_TEST
 IS
 SELECT FIRST_NAME,LAST_NAME,
 ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS EXPER
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=&DID;
 
 EXPER NUMBER;
 FNAME VARCHAR2(20);
 LNAME VARCHAR2(20);
BEGIN
OPEN EMP_TEST;
 LOOP
    FETCH EMP_TEST INTO FNAME,LNAME,EXPER;
    DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||EXPER);
   EXIT WHEN EMP_TEST%NOTFOUND;
 END LOOP;
CLOSE EMP_TEST;
END;






--===========================================
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_TEST
 IS
 SELECT 
  E.FIRST_NAME,E.LAST_NAME,E.SALARY,D.DEPARTMENT_NAME,
  ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS EXPER
  FROM EMPLOYEES E JOIN DEPARTMENTS D
  ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
  WHERE E.DEPARTMENT_ID=&DID;
  
  
  FNAME VARCHAR2(20);
  LNAME VARCHAR2(20);
  SAL NUMBER;
  DNAME VARCHAR2(20);
  EXPER NUMBER;
  
BEGIN
 OPEN EMP_TEST;
 LOOP
     FETCH EMP_TEST INTO FNAME,LNAME,SAL,DNAME,EXPER ;
     DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '|| SAL||' '||DNAME||' '|| EXPER);
     EXIT WHEN EMP_TEST%NOTFOUND;
 END LOOP;
 CLOSE EMP_TEST;
END;

---=====================================================================
--FETCH FIRST_NAME,LAST_NAME,EXPERIENCE,CITY
SET SERVEROUTPUT ON
DECLARE
    CURSOR EMP_CUR
    IS
    SELECT 
    E.FIRST_NAME,
    E.LAST_NAME,
    D.DEPARTMENT_NAME,
    L.CITY,
    ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS TOTAL_EXPER
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
    JOIN LOCATIONS L 
    ON (D.LOCATION_ID=L.LOCATION_ID)
    WHERE D.DEPARTMENT_ID=&DID;
    
    TOTAL_EXPER NUMBER;
    FNAME  VARCHAR2(20);
    LNAME VARCHAR2(20);
    DNAME VARCHAR2(20);
    CITY VARCHAR2(20);
    
BEGIN
   OPEN EMP_CUR;
   LOOP 
    FETCH EMP_CUR INTO FNAME,LNAME,DNAME,CITY,TOTAL_EXPER;
    DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||CITY||' '||TOTAL_EXPER||' '||DNAME);
    EXIT WHEN EMP_CUR%NOTFOUND;
   END LOOP;
   CLOSE EMP_CUR;
END;

--=========================================================================
--FETCH FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NAME,CITY,
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CUR 
 IS
 SELECT 
   E.FIRST_NAME,
   E.LAST_NAME,
   E.SALARY,
   D.DEPARTMENT_NAME,
   L.CITY,
   ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS TOTAL_EXP
   FROM EMPLOYEES E JOIN DEPARTMENTS D
   ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
   JOIN LOCATIONS L
   ON(D.LOCATION_ID=L.LOCATION_ID)
   WHERE D.DEPARTMENT_ID=&DID;
   
   
   TOTAL_EXP NUMBER;
   FNAME  VARCHAR2(20);
   LNAME VARCHAR2(20);
   SAL NUMBER;
   DNAME  VARCHAR2(20);
   CITY VARCHAR2(20);
   EXPER NUMBER;
BEGIN
 OPEN EMP_CUR;
  LOOP
        FETCH EMP_CUR INTO FNAME,LNAME,SAL,DNAME,CITY,EXPER;
        DBMS_OUTPUT.PUT_LINE(FNAME||' '||' '||LNAME||' '||SAL||' '||DNAME||' '||CITY||' '|| EXPER);
     EXIT WHEN EMP_CUR%NOTFOUND;
  END LOOP;
 CLOSE EMP_CUR;
END;



--==================================================
--FETCH FIRST_NAME,      
SET SERVEROUTPUT ON
DECLARE
BEGIN
END;

