SELECT FIRST_NAME,LAST_NAME,SUBSTR(FIRST_NAME,1,3) AS F_SRT
FROM EMPLOYEES ;

-- USER DEFINED FUNTIONS

CREATE OR REPLACE FUNCTION CAL_EXP(EID NUMBER)
RETURN NUMBER
AS
EXPER NUMBER;

BEGIN
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0) INTO EXPER
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;

RETURN EXPER ;
END;


