SET SERVEROUTPUT ON
DECLARE

TYPE EMP_REC IS RECORD         --HERE WE HAVE DECLARE DATA TYPE
(
FNAME VARCHAR2(20),
LNAME VARCHAR2(20),
SAL NUMBER
);

EMP_DETAILS EMP_REC;            --HERE WE HAVE USED DECLARED DATA TYPE INTO VARIABLE EMP_DETAILS

CURSOR EMP_CUR IS             --HERE WE HAVE USED CURSOR TO FETCH MULTIPLE RECORDS
SELECT FIRST_NAME ,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30 ;

BEGIN

OPEN EMP_CUR;
LOOP
FETCH EMP_CUR INTO EMP_DETAILS ;
DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME ||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL);
EXIT WHEN EMP_CUR%NOTFOUND;
END LOOP;
CLOSE EMP_CUR;
END;

--=======================================================================
SET SERVEROUTPUT ON 
DECLARE
   TYPE EMP_REC IS RECORD(    
    FNAME VARCHAR2(20),
    LNAME VARCHAR2(20),
    SAL NUMBER,
    HIRE_D DATE
   );
   
 EMP_DETAILS EMP_REC;
 
   CURSOR EMP_CUR 
   IS
   SELECT FIRST_NAME,LAST_NAME,SALARY,HIRE_DATE
   FROM EMPLOYEES
   WHERE DEPARTMENT_ID=&DID;
BEGIN
  OPEN  EMP_CUR;
LOOP
FETCH EMP_CUR INTO EMP_DETAILS;
DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL||' '||EMP_DETAILS.HIRE_D);
        EXIT WHEN EMP_CUR%NOTFOUND;
       END LOOP;
  CLOSE EMP_CUR;
END;

--===============================================================================
SET SERVEROUTPUT ON
DECLARE
  TYPE EMP_REC IS RECORD(     --THIS WE HAVE DECLARED DATATYPE
   FNAME VARCHAR2(20),
   LNAME VARCHAR2(20),
   SAL NUMBER,
   HIRE_D DATE,
   JOBID VARCHAR2(30)
 );
 
 EMP_DETAILS EMP_REC;
 
   CURSOR EMP_CUR 
   IS
   SELECT FIRST_NAME,LAST_NAME,SALARY,HIRE_DATE,JOB_ID
   FROM EMPLOYEES
   WHERE DEPARTMENT_ID=&DID;
BEGIN
   OPEN EMP_CUR;
      LOOP
            FETCH EMP_CUR INTO EMP_DETAILS;
            DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL);
            EXIT WHEN EMP_CUR%NOTFOUND;
      END LOOP;
   CLOSE EMP_CUR;
END;




--=============================================================================
SET SERVEROUTPUT ON
DECLARE
 TYPE EMP_REC IS RECORD
 ( FNAME VARCHAR2(20),
   LNAME VARCHAR2(20),
   SAL NUMBER,
   JOB_ID VARCHAR2(20)
 );
 
 EMP_DETAILS EMP_REC;
  
  CURSOR EMP_CUR 
  IS
  SELECT FIRST_NAME,LAST_NAME,SALARY,JOB_ID
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID=&DID;
  
  
BEGIN
  OPEN EMP_CUR;
     LOOP
          FETCH EMP_CUR INTO EMP_DETAILS
     END LOOP;
  CLOSE EMP_CUR;
END;

--=================================================================================
SET SERVEROUTPUT ON
DECLARE
 TYPE EMP_REC IS RECORD    --HERE WE HAVE DECLARED DATAYPE
 ( 
 FNAME VARCHAR2(20),
 LNAME VARCHAR2(20),
 SAL NUMBER,
 HIRE_D DATE
 );
 EMP_DETAILS EMP_REC;
 
 CURSOR EMP_CUR 
 IS
 SELECT FIRST_NAME,LAST_NAME,SALARY,HIRE_DATE
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=&DID;
 
 
BEGIN
     OPEN EMP_CUR;
      LOOP
          FETCH EMP_CUR INTO EMP_DETAILS;    --THIS IS A COMPOSITE VARIABLE
          DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL||' '||EMP_DETAILS.HIRE_D);
          EXIT WHEN EMP_CUR%NOTFOUND;
      END LOOP;
     CLOSE EMP_CUR;
END;



--============================================================================
--FETCH FIRST_NAME,LAST_NAME,SALARY
SET SERVEROUTPUT ON
DECLARE
 TYPE EMP_REC IS RECORD
 (
 
 );
  
BEGIN

END;
--===========================================================================
--FETCH FIRST_NAME,LAST_NAME,SALARY
SET SERVEROUTPUT ON
DECLARE
       TYPE EMP_REC IS RECORD(
        FNAME VARCHAR2(20),
        LNAME VARCHAR2(20),
        SAL NUMBER
       );
       
BEGIN
END;

-------------------------------------------------------------------------------------------
--FETCH FIRST_NAME,LAST_NAME,SALARY
SET SERVEROUTPUT ON
DECLARE
  TYPE EMP_REC IS RECORD (
   FNAME VARCHAR2(30),
   LNAME VARCHAR2(30),
   SAL NUMBER
  );
 EMP_DETAILS EMP_REC; 

CURSOR EMP_CUR 
IS
 SELECT FIRST_NAME,LAST_NAME,SALARY
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=&DID;
  
BEGIN
   OPEN EMP_CUR;
     LOOP
         FETCH EMP_CUR INTO EMP_DETAILS;
         EXIT WHEN EMP_CUR%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL);
     END LOOP;
   CLOSE EMP_CUR;
END;

--======================================================================================================
--FETCH FIRST_NAME,LAST_NAME,SALARY,EXPERIENCE,

SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_CONTEXT 
 IS
  SELECT FIRST_NAME,LAST_NAME,SALARY,
  ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS TOTAL_EXP
  FROM EMPLOYEES;
 
BEGIN
 FOR I IN EMP_CONTEXT
 LOOP
  DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.TOTAL_EXP||' '||I.SALARY);
 END LOOP;
END;


--==================================================================================
SET SERVEROUTPUT ON
DECLARE
 TYPE EMP_REC IS RECORD(   --HERE I DECLARE DATATYPE
 F_NAME VARCHAR2(20),
 L_NAME VARCHAR2(20),
 SAL NUMBER
 );
 
 EMP_DETAILS EMP_REC;        --HERE I ACCESSED THAT DATATYPE INTO VARIABLE
  
  CURSOR EMP_CONTEXT 
  IS
  SELECT 
  FIRST_NAME,
  LAST_NAME,
  SALARY
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID=30;
 
BEGIN
  OPEN EMP_CONTEXT;
     LOOP
       FETCH EMP_CONTEXT INTO EMP_DETAILS ;
     EXIT WHEN EMP_CONTEXT%NOTFOUND;
     DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL);
     END LOOP;
  CLOSE EMP_CONTEXT;
END;


--=====================================================================
SET SERVEROUTPUT ON
DECLARE
 TYPE EMP_REC IS RECORD(
    FNAME VARCHAR2(20),
    LNAME VARCHAR2(20),
    SAL NUMBER
 );
 EMP_DETAILS EMP_REC;
 
 CURSOR EMP_CUR 
 IS
 SELECT
 FIRST_NAME,LAST_NAME,SALARY
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=&DID;
 
BEGIN
OPEN EMP_CUR;
 LOOP
  FETCH EMP_CUR INTO EMP_DETAILS;
     EXIT WHEN EMP_CUR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.FNAME||' '||EMP_DETAILS.LNAME||' '||EMP_DETAILS.SAL);
 END LOOP;
 CLOSE EMP_CUR;
END;

--=================================================================







